spring:
  application:
    name: trackcar-service
traccar:
  url: http://34.44.187.33:8082
  email: luckyraj2307@gmail.com
  password: Pr!nce@2307

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka